Implement Create Reminder Functionality
NikolaVetnic/Timelines pull request #15
Opened 2024-12-20 14:07 UTC by HunorTotBagi

This PR closes #14

2024-12-25 13:37 UTC, NikolaVetnic requested changes

2024-12-25 13:37 UTC, NikolaVetnic commented on Backend/src/Modules/Reminders/Reminders.Application/Dtos/ReminderDto.cs
> +    string Priority,
I think it makes more sense if `Priority` is an integer.

2024-12-25 13:37 UTC, NikolaVetnic commented on Backend/src/Modules/Reminders/Reminders.Domain/Models/Reminder.cs
> +    public void Update(string title)
Why just the title? It would make sense to make all the fields (other than ID of course) updateable.

2024-12-25 13:37 UTC, NikolaVetnic commented on Backend/src/Modules/Reminders/Reminders.Domain/ReminderDomainTestClass.cs
> +public class ReminderDomainTestClass
Delete this class as it is used nowhere. Do the same for the corresponding class in the `Nodes` module.

2024-12-25 13:37 UTC, NikolaVetnic commented on Backend/src/Modules/Reminders/Reminders.Infrastructure/Data/Configurations/ReminderConfiguration.cs
> +        // ToDO: Add remaining Reminder configuration commands
Please use `ToDo` :)

2024-12-25 14:58 UTC, HunorTotBagi commented on Backend/src/Modules/Reminders/Reminders.Domain/Models/Reminder.cs
> +    public void Update(string title)
This is my bad, because initially only the `Title` property was present. Later when I added the rest I forgot the add them to the `Update` method.

✅

2024-12-25 14:58 UTC, HunorTotBagi commented on Backend/src/Modules/Reminders/Reminders.Application/Dtos/ReminderDto.cs
> +    string Priority,
✅

2024-12-25 15:05 UTC, HunorTotBagi commented on Backend/src/Modules/Reminders/Reminders.Infrastructure/Data/Configurations/ReminderConfiguration.cs
> +        // ToDO: Add remaining Reminder configuration commands
I added some, please check if they are good enough ✅

2024-12-26 07:40 UTC, NikolaVetnic commented on Backend/src/Modules/Reminders/Reminders.Infrastructure/Data/Configurations/ReminderConfiguration.cs
> +        // ToDO: Add remaining Reminder configuration commands
We'll redefine these at a later point, good enough for now.

2024-12-26 07:41 UTC, NikolaVetnic approved these changes

2024-12-26 07:49 UTC, merged