Implement Create Reminder Functionality
NikolaVetnic/Timelines pull request #18
Opened 2024-12-25 11:06 UTC by HunorTotBagi

This PR Closes #17

2024-12-26 16:10 UTC, NikolaVetnic requested changes
In essence, `FileAsset` is the entity and `Files` is the name of the module. Maybe I've been inconsistent with my renaming requests, if you think I made a mistake please write so we can clarify.

2024-12-26 16:10 UTC, NikolaVetnic commented on Backend/src/Applications/Core/Core.Api/Extensions/DatabaseExtensions.cs
> +        await services.MigrateAndSeedFilesDatabaseAsync();
Move this one to the top - let's keep the lexographic order whenever we list similar things in different modules.

2024-12-26 16:10 UTC, NikolaVetnic commented on Backend/src/Modules/Files/Files.Api/Endpoints/CreateFile.cs
> +            .WithName("CreateFile")
Use `File Asset` in this and two subsequent calls.

2024-12-26 16:10 UTC, NikolaVetnic commented on Backend/src/Modules/Files/Files.Application/Dtos/FileAssetDto.cs
> +public record FileAssetDto(
I've added `NodeId` to `NodeDto` in my latest PR, I think you should do the same here and in Reminders.

2024-12-26 16:10 UTC, NikolaVetnic commented on Backend/src/Modules/Files/Files.Application/Files/Commands/CreateFile/CreateFileCommand.cs
> +public record CreateFileCommand(FileAssetDto FileAsset) : ICommand<CreateFileResult>;
Use `FileAsset` here.

2024-12-26 16:10 UTC, NikolaVetnic commented on Backend/src/Modules/Files/Files.Application/Files/Commands/CreateFile/CreateFileHandler.cs
> +public class CreateFileHandler(IFilesDbContext dbContext) :
`FileAsset`.

2024-12-26 16:10 UTC, NikolaVetnic commented on Backend/src/Modules/Files/Files.Domain/Events/FileCreatedEvent.cs
> +public record FileCreatedEvent(FileAsset FileAsset) : IDomainEvent;
`FileAsset`.

2024-12-26 16:10 UTC, NikolaVetnic commented on Backend/src/Modules/Files/Files.Domain/Events/FileUpdatedEvent.cs
> +public record FileUpdatedEvent(FileAsset FileAsset) : IDomainEvent;
`FileAsset`.

2024-12-26 19:37 UTC, HunorTotBagi commented on Backend/src/Applications/Core/Core.Api/Extensions/DatabaseExtensions.cs
> +        await services.MigrateAndSeedFilesDatabaseAsync();
Good catch, I agree with you ✅

2024-12-26 19:41 UTC, HunorTotBagi commented on Backend/src/Modules/Files/Files.Application/Dtos/FileAssetDto.cs
> +public record FileAssetDto(
✅

2024-12-26 19:46 UTC, HunorTotBagi commented on Backend/src/Modules/Files/Files.Application/Files/Commands/CreateFile/CreateFileCommand.cs
> +public record CreateFileCommand(FileAssetDto FileAsset) : ICommand<CreateFileResult>;
✅

2024-12-26 19:46 UTC, HunorTotBagi commented on Backend/src/Modules/Files/Files.Application/Files/Commands/CreateFile/CreateFileHandler.cs
> +public class CreateFileHandler(IFilesDbContext dbContext) :
✅

2024-12-26 19:47 UTC, HunorTotBagi commented on Backend/src/Modules/Files/Files.Domain/Events/FileCreatedEvent.cs
> +public record FileCreatedEvent(FileAsset FileAsset) : IDomainEvent;
✅

2024-12-26 19:47 UTC, HunorTotBagi commented on Backend/src/Modules/Files/Files.Domain/Events/FileUpdatedEvent.cs
> +public record FileUpdatedEvent(FileAsset FileAsset) : IDomainEvent;
✅

2024-12-26 19:57 UTC, HunorTotBagi commented on Backend/src/Modules/Files/Files.Api/Endpoints/CreateFile.cs
> +            .WithName("CreateFile")
✅

2024-12-27 07:22 UTC, NikolaVetnic commented on Backend/src/Modules/Files/Files.Application/Files/Commands/CreateFile/CreateFileCommand.cs
> +public record CreateFileCommand(FileAssetDto FileAsset) : ICommand<CreateFileResult>;
You left `CreateFileResult` here.

2024-12-27 07:23 UTC, NikolaVetnic commented on Backend/src/Modules/Files/Files.Application/Files/Commands/CreateFile/CreateFileHandler.cs
> +public class CreateFileHandler(IFilesDbContext dbContext) :
`CreateFileResult`, but this will be updated automatically once you rename the class.

2024-12-27 07:24 UTC, NikolaVetnic requested changes
You missed `CreateFileResult`, other than that - ALL GUD.

2024-12-27 07:28 UTC, HunorTotBagi commented on Backend/src/Modules/Files/Files.Application/Files/Commands/CreateFile/CreateFileHandler.cs
> +public class CreateFileHandler(IFilesDbContext dbContext) :
✅

2024-12-27 07:28 UTC, HunorTotBagi commented on Backend/src/Modules/Files/Files.Application/Files/Commands/CreateFile/CreateFileCommand.cs
> +public record CreateFileCommand(FileAssetDto FileAsset) : ICommand<CreateFileResult>;
✅

2024-12-27 07:30 UTC, NikolaVetnic approved these changes

2024-12-27 08:48 UTC, merged