Add Cross-Cutting Concerns and Apply Them to the Nodes Module
NikolaVetnic/Timelines pull request #21
Opened 2024-12-26 09:39 UTC by NikolaVetnic

In this PR I have done the following:
- I have added FluentValidation to the solution.
- I have introduced custom exception handling to the solution, as well as the Get Node by Id feature to test the implementation.
- I have added logging behavior to the MediatR handling.
- I have added paginated response to the solution, as well as the List Nodes feature to test the implementation.
- I have implemented database interceptors concerned with updating entity fields and dispatching domain events.

Closes #20 .

2024-12-26 20:40 UTC, HunorTotBagi requested changes

2024-12-26 20:40 UTC, HunorTotBagi commented on Backend/src/BuildingBlocks/BuildingBlocks.Application/Behaviors/LoggingBehavior.cs
> +    where TRequest : notnull, IRequest<TResponse>
When I hover over `notnull` in line 9 it says: The `notnull` constraint is redundant because type parameter `TRequest` is constrained by non-nullable type `IRequest<TResponse>`. Maybe consider removing it, although I don't know can this affect something else.

2024-12-26 20:40 UTC, HunorTotBagi commented on Backend/src/BuildingBlocks/BuildingBlocks.Application/Cqrs/ICommand.cs
Consider removing `{ }` and use `;` instead. Resharper suggest that it is a  redundant empty interface declaration body.

2024-12-26 20:40 UTC, HunorTotBagi commented on Backend/src/BuildingBlocks/BuildingBlocks.Application/Cqrs/ICommandHandler.cs
Consider removing `{ }` and use `;` instead. Resharper suggest that it is a  redundant empty interface declaration body.

2024-12-26 20:40 UTC, HunorTotBagi commented on Backend/src/BuildingBlocks/BuildingBlocks.Application/Cqrs/IQuery.cs
Consider removing `{ }` and use `;` instead. Resharper suggest that it is a  redundant empty interface declaration body.

2024-12-26 20:40 UTC, HunorTotBagi commented on Backend/src/BuildingBlocks/BuildingBlocks.Application/Cqrs/IQueryHandler.cs
Consider removing `{ }` and use `;` instead. Resharper suggest that it is a  redundant empty interface declaration body.

2024-12-26 20:40 UTC, HunorTotBagi commented on Backend/src/Modules/Nodes/Nodes.Api/Endpoints/Nodes/ListNodes.cs
Since now there is three files in `Endpoints` -> `Nodes` I can see that there is six using that could be moved to a `GlobalUsing` file. What do you think about this idea?

```csharp
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Routing;
global using Microsoft.AspNetCore.Http;
global using MediatR;
global using Mapster;
global using Carter;
```

2024-12-26 20:40 UTC, HunorTotBagi commented on Backend/src/Modules/Nodes/Nodes.Application/Entities/Nodes/Queries/GetNodeById/GetNodeByIdHandler.cs
> +using Nodes.Application.Entities.Nodes.Dtos;
Using directive is not required by the code and can be safely removed.

2024-12-26 20:40 UTC, HunorTotBagi commented on Backend/src/Modules/Nodes/Nodes.Infrastructure/Data/Interceptors/AuditableEntityInterceptor.cs
```csharp
global using BuildingBlocks.Domain.Abstractions;
```
could be moved to the `GlobalUsing` file since it is used twice in `Interceptors` folder. If you decide to do so, please remove it from `AuditableEntityInterceptor` and `DispatchDomainEventsInterceptor`

2024-12-27 07:08 UTC, NikolaVetnic commented on Backend/src/BuildingBlocks/BuildingBlocks.Application/Behaviors/LoggingBehavior.cs
> +    where TRequest : notnull, IRequest<TResponse>
I think not, removed.

2024-12-27 07:16 UTC, NikolaVetnic commented on Backend/src/BuildingBlocks/BuildingBlocks.Application/Cqrs/ICommand.cs
✅

2024-12-27 09:35 UTC, NikolaVetnic commented on Backend/src/BuildingBlocks/BuildingBlocks.Application/Cqrs/ICommandHandler.cs
✅

2024-12-27 09:35 UTC, NikolaVetnic commented on Backend/src/BuildingBlocks/BuildingBlocks.Application/Cqrs/IQuery.cs
✅

2024-12-27 09:35 UTC, NikolaVetnic commented on Backend/src/BuildingBlocks/BuildingBlocks.Application/Cqrs/IQueryHandler.cs
✅

2024-12-27 09:53 UTC, NikolaVetnic commented on Backend/src/Modules/Nodes/Nodes.Api/Endpoints/Nodes/ListNodes.cs
Sure, why not :)

2024-12-27 09:55 UTC, NikolaVetnic commented on Backend/src/Modules/Nodes/Nodes.Application/Entities/Nodes/Queries/GetNodeById/GetNodeByIdHandler.cs
> +using Nodes.Application.Entities.Nodes.Dtos;
✅

2024-12-27 09:58 UTC, NikolaVetnic commented on Backend/src/Modules/Nodes/Nodes.Infrastructure/Data/Interceptors/AuditableEntityInterceptor.cs
✅

2024-12-27 11:56 UTC, HunorTotBagi commented on Backend/src/Modules/Nodes/Nodes.Application/Entities/Nodes/Queries/GetNodeById/GetNodeByIdHandler.cs
> +using Nodes.Application.Entities.Nodes.Dtos;
It seems to me that you did not apply these changes, and I double checked I pulled on the branch.

2024-12-27 19:04 UTC, HunorTotBagi reviewed
I tested the following scenarios:

- Creating `Node` without `Title` returns `NullReferenceException` ✅
- Creating `Node` with `Title` returns `NullReferenceException` ❌ 
- Passing wrong Id to Get Node by Id throws `NodeNotFoundException` ✅
- Passing existing Node Id to Get Node by Id correctly returns that `Node` ✅

2024-12-27 19:49 UTC, HunorTotBagi approved these changes
More scenarios were tested:
- One can create new `Node` 
- Title indeed cannot exceed 100 characters, the correct exception is thrown
- Description indeed cannot exceed 500 characters, the correct exception is thrown
- Pagination is working correctly

2024-12-27 19:55 UTC, merged