Add Cross-Cutting Concerns and Apply Them to the Notes Module
NikolaVetnic/Timelines pull request #37
Opened 2024-12-30 16:54 UTC by NikolaDmitrasinovic

# Description
Notes module is refactored and extended to support newly added features such as:
- custom exception handling
- logging behavior
- paginated response when listing ( in this case Notes )
- database interceptors

2024-12-30 19:16 UTC, HunorTotBagi requested changes
After manual test I can conclude that everything is working as intended ✅

Additionally, please create a `Notes` folder within the `Endpoints` directory and move the following files into this folder: `CreateNote`, `GetNoteById`, and `ListNotes`. This structure will be beneficial in the future, especially if new entities are introduced.

![image](https://github.com/user-attachments/assets/28058480-56c4-4e7f-98d3-4cad46243b35)

2024-12-30 19:16 UTC, HunorTotBagi commented on Backend/src/Modules/Notes/Notes.Application/Entities/Notes/Queries/GetNoteById/GetNoteByIdHandler.cs
> +    public async Task<GetNoteByIdResult> Handle(GetNoteByIdQuery request, CancellationToken cancellationToken)
Please rename the parameter from `request` to `query`. I understand that it is referred to as `request` in the `Nodes` module, but this will be addressed in my upcoming pull request.

2024-12-31 07:35 UTC, NikolaDmitrasinovic commented on Backend/src/Modules/Notes/Notes.Api/Endpoints/CreateNote.cs
> +using Notes.Application.Entities.Notes.Dtos;
done

2024-12-31 07:37 UTC, NikolaDmitrasinovic commented on Backend/src/Modules/Notes/Notes.Api/Endpoints/GetNotesById.cs
note

2024-12-31 07:37 UTC, NikolaDmitrasinovic commented on Backend/src/Modules/Notes/Notes.Api/Extensions/ServiceCollectionExtensions.cs
done

2024-12-31 07:41 UTC, NikolaDmitrasinovic commented on Backend/src/Modules/Notes/Notes.Application/Entities/Notes/Queries/GetNoteById/GetNoteByIdHandler.cs
> +    public async Task<GetNoteByIdResult> Handle(GetNoteByIdQuery request, CancellationToken cancellationToken)
done

2024-12-31 07:45 UTC, NikolaDmitrasinovic commented on Backend/src/Modules/Notes/Notes.Application/Entities/Notes/Commands/CreateNote/CreateNoteHandler.cs
>  public class CreateNoteHandler(INotesDbContext dbContext)
Could you please elaborate on logic behind internal handler class?

2024-12-31 08:00 UTC, NikolaDmitrasinovic commented on Backend/src/Modules/Notes/Notes.Application/Entities/Notes/Commands/CreateNote/CreateNoteHandler.cs
>  public class CreateNoteHandler(INotesDbContext dbContext)
I have found out that it is considered best practice when using MediatR to make your handlers internal ( especially if modular architecture ), but this is done completely randomly and arbitrary across this project, including Nodes module.

2024-12-31 11:47 UTC, HunorTotBagi approved these changes

2025-01-03 07:44 UTC, NikolaVetnic approved these changes

2025-01-03 07:44 UTC, merged